### ISSUE TITLE
Support for Require claim directive

### ISSUE THREAD

**Issue by chilt-payx** [zmartzone/mod_oauth2#1]
We were looking to use mod_auth_openidc as a resource server, but saw the deprecation comments in the sample config referencing this plug-in.  We need to validate the audience (aud) field in our access token.  Is this supported?  I reviewed the sample config file provided, but did not see a way to do this.

**Comment by zandbelt** [comment]
The current state of things is that you cannot (yet) use any native `Require claim aud:<>` directive that you would use in `mod_auth_openidc`. What you can do today is inspect the `OAUTH2_CLAIM_aud` header value that will be sent to the backend in your application. I hope that is still a valid option for you...

**Comment by chilt-payx** [comment]
Unfortunately that will not work for our use case - we want to do the audience validation in the DMZ, which means it must be done in the web tier.  Would you recommend we use mod_auth_openidc at this time?  Do you expect to support this type of validation in the future?

**Comment by zandbelt** [comment]
I recommend that you use mod_auth_openidc for the time being indeed. I am turning this into a feature request.

**Comment by zandbelt** [comment]
would you be able to test the latest commit? I have added support for Require claim directives...

**Comment by chilt-payx** [comment]
> would you be able to test the latest commit? I have added support for Require claim directives...

Is there an RPM installer available that I can use to install it on a test server of ours?

**Comment by zandbelt** [comment]
see: https://github.com/zmartzone/mod_oauth2/releases/tag/v3.0.1

**Comment by zandbelt** [comment]
Any luck with testing?

**Comment by chilt-payx** [comment]
> Any luck with testing?

Sorry, we had a holiday weekend and I am just getting caught up from that.  I should be able to run some tests tomorrow (May 31).

**Comment by zandbelt** [comment]
how did it work out?

**Comment by GRRedWings** [comment]
How do I use these claims?  Is it possible to set a specific hd that I want in the jwt?

**Comment by zandbelt** [comment]
you need `Require oauth2_claim hd:mySite.com`

**Comment by GRRedWings** [comment]
Thank you for the quick reply, is it possible to chain multiple together?

I have tried 
Require oauth2_claim hd:mySite.com and email:me@mySite.com
Require oauth2_claim hd:mySite.com:oauth2_claim email:me@mySite.com

It seems to only take the last item, and the first item is ignored.

**Comment by zandbelt** [comment]
By default Apache considers this as a logical OR, in 2.4.x you can use RequireAll to create a logical AND.
See https://httpd.apache.org/docs/2.4/mod/mod_authz_core.html#requireall In your case:
```apache
<RequireAll>
    Require oauth2_claim hd:mySite.com
    Require oauth2_claim email:me@mySite.com
</RequireAll>
```

**Comment by GRRedWings** [comment]
Again, thank you for the quick response!  I appreciate the work you have done with this and helping those that don't have the strong understanding of Oauth that you do.
