### ISSUE TITLE
How to install mod_oauth2

### ISSUE THREAD

**Issue by astro-fly** [zmartzone/mod_oauth2#10]
Hi, sorry for simple question but,
cannot find a proper sequence on how to install. Wiki redirects back to home page.
My challenge is with a tree of dependencies for all the required modules, seems like i am doing smth wrong.
Would be great if someone can share a simple logic on how to install the module.

PS. We are currently using mod_auth_openidc, but I came here because there was a message that it is deprecated and is being replaced by this module.

Thanks.

**Comment by zandbelt** [comment]
see the notes on the release page: https://github.com/zmartzone/mod_oauth2/releases/tag/v3.1.0
