### ISSUE TITLE
Error Using Pubkey

### ISSUE THREAD

**Issue by GRRedWings** [zmartzone/mod_oauth2#11]
I have created my own JWT, and I'm trying to use this to secure my api. When I try to configure apache to use it, I get the following error from a configtest

AH00526: Syntax error on line 16 of /etc/apache2/sites-enabled/mySite.conf:
PEM_read_bio_PUBKEY failed: error:0909006C:PEM routines:get_name:no start line
Action 'configtest' failed.

I had used Steps 1 & 2 here which got me my public RSA key
https://adangel.org/2016/08/29/openssl-rsa-java/

Here is the configuration I have in my conf file. I read that liboauth2 is a requirement. I downloaded and ran the install, but I'm not sure if maybe I didn't install that properly, or if there is something else I missed.

The other thing I have tried, instead of passing a path to the pem, I tried to paste in the contents, but that complained about the number of arguments for OAuth2TokenVerify.
   
```
<Location /secure>
      AllowOverride All
      AuthType oauth2
      OAuth2TokenVerify pubkey /home/myUser/apache/rsa-public.pem kid=123456789000-b425-4450-8952-87fec8bcffc2ffd&verify.iss=skip&verify.exp=skip
</Location>
```

**Comment by zandbelt** [comment]
the `pubkey` option is supposed to be configured with a PEM-formatted public key value as in:
```apache
OAuth2TokenVerify pubkey "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAofgWCuLjybRlzo0tZWJjNiuSfb4p4fAkd/wWJcyQoTbji9k0l8W26mPddxHmfHQp+Vaw+4qPCJrcS2mJPMEzP1Pt0Bm4d4QlL+yRT+SFd2lZS+pCgNMsD1W/YpRPEwOWvG6b32690r2jZ47soMZo9wGzjb/7OMg0LOL+bSf63kpaSHSXndS5z5rexMdbBYUsLA9e+KXBdQOS+UTo7WTBEMa2R2CapHg665xsmtdVMTBQY4uDZlxvb3qCo5ZwKh9kG4LT6/I5IhlJH7aGhyxXFvUK+DWNmoudF8NAco9/h9iaGNj8q2ethFkMLs91kzk2PAcDTW9gb54h4FRWyuXpoQIDAQAB-----END PUBLIC KEY-----"
```
but I haven't quite figured out how to configure this in Apache with the right line breaks; for now you can convert the key into JWK format and configure it with `jwk` as in:
```apache
OAuth2TokenVerify jwk "{\"kty\":\"RSA\",\"kid\":\"one\",\"use\":\"sig\",\"n\":\"12SBWV_4xU8sBEC2IXcakiDe3IrrUcnIHexfyHG11Kw-EsrZvOy6PrrcqfTr1GcecyWFzQvUr61DWESrZWq96vd08_iTIWIny8pU5dlCoC7FsHU_onUQI1m4gQ3jNr00KhH878vrBVdr_T-zuOYQQOBRMEyFG-I4nb91zO1n2gcpQHeabJw3JIC9g65FCpu8DSw8uXQ1hVfGUDZAK6iwncNZ1uqN4HhRGNevFXT7KVG0cNS8S3oF4AhHafFurheVxh714R2EseTVD_FfLn2QTlCss_73YIJjzn047yKmAx5a9zuun6FKiISnMupGnHShwVoaS695rDmFvj7mvDppMQ\",\"e\":\"AQAB\" }"
```

**Comment by GRRedWings** [comment]
I'm guessing you've thought of this and maybe there is some security concern, but would it make sense to have a  pubkey_file that takes a path?

**Comment by zandbelt** [comment]
it does make sense if I cannot get pubkey value to work...

**Comment by GRRedWings** [comment]
With your help I was able to get it to work using jwk instead of pubkey. Thank you so much for the help and library!
