### ISSUE TITLE
Trouble setting up on Centos 7

### ISSUE THREAD

**Issue by GRRedWings** [zmartzone/mod_oauth2#12]
I have tried to get this running on Centos 7.  I am currently experiencing this error
httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/conf.modules.d/10-oauth2.conf: Cannot load modules/mod_oauth2.so into server: /usr/lib64/liboauth2.so.0: undefined symbol: cjose_jwk_import_json

After installing httpd and configurating my conf file, I have run the following

wget https://github.com/zmartzone/mod_auth_openidc/releases/download/v2.3.0/cjose-0.5.1-1.el7.centos.x86_64.rpm
rpm -iv ~/cjose-0.5.1-1.el7.centos.x86_64.rpm --nodeps

wget https://github.com/zmartzone/liboauth2/releases/download/v1.4.0.1/liboauth2-1.4.0.1-1.el7.x86_64.rpm
sudo yum localinstall -y liboauth2-1.4.0.1-1.el7.x86_64.rpm

wget https://github.com/zmartzone/liboauth2/releases/download/v1.4.0.1/liboauth2-apache-1.4.0.1-1.el7.x86_64.rpm
sudo yum localinstall -y liboauth2-apache-1.4.0.1-1.el7.x86_64.rpm

wget https://github.com/zmartzone/mod_oauth2/releases/download/v3.2.0/mod_oauth2-3.2.0-1.el7.x86_64.rpm
sudo yum localinstall -y mod_oauth2-3.2.0-1.el7.x86_64.rpm

Seeing someone had a similar issue with mod_auth_openidc, this is where I found cjose from. I did not install the 2 jansson libraries but rpm -qa shows me they are already installed and the same version you referenced.

**Comment by zandbelt** [comment]
I've successfully used https://mod-auth-openidc.org/download/cjose-0.6.1.5-1.el7.x86_64.rpm on my Docker Centos 7 instances, can you try that?

**Comment by GRRedWings** [comment]
Thanks!  That seems to have fixed the cjose error. Sorry I didn't check to see if there was a newer version of the library.

**Comment by GRRedWings** [comment]
You mention docker, do you have any scripts that show how to run this in docker? I've spent some time trying to add it on to httpd:2.4 and facing a growing number of imports I'm needing to pull in.

**Comment by zandbelt** [comment]
```Dockerfile
FROM centos:centos7
MAINTAINER Hans Zandbelt <hans.zandbelt@zmartzone.eu>

RUN yum install -y epel-release
RUN yum update -y

RUN yum -y swap -- remove fakesystemd -- install systemd systemd-libs
RUN yum -y update; yum clean all; \
	(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
	rm -f /lib/systemd/system/multi-user.target.wants/*;\
	rm -f /etc/systemd/system/*.wants/*;\
	rm -f /lib/systemd/system/local-fs.target.wants/*; \
	rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
	rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
	rm -f /lib/systemd/system/basic.target.wants/*;\
	rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]

ENV CJOSE_VERSION 0.6.1.5
ENV CJOSE_PKG cjose-${CJOSE_VERSION}-1.el7.x86_64.rpm
COPY ${CJOSE_PKG} /root/${CJOSE_PKG}
RUN ${CMD_PREFIX} yum localinstall -y /root/${CJOSE_PKG}

RUN yum install -y hiredis libmemcached

ENV LIBOAUTH2_VERSION 1.4.0
ENV LIBOAUTH2_PKG liboauth2-${LIBOAUTH2_VERSION}-1.el7.x86_64.rpm
COPY ${LIBOAUTH2_PKG} /root/${LIBOAUTH2_PKG}
RUN ${CMD_PREFIX} yum localinstall -y /root/${LIBOAUTH2_PKG}

ENV LIBOAUTH2_PKG liboauth2-apache-${LIBOAUTH2_VERSION}-1.el7.x86_64.rpm
COPY ${LIBOAUTH2_PKG} /root/${LIBOAUTH2_PKG}
RUN ${CMD_PREFIX} yum localinstall -y /root/${LIBOAUTH2_PKG}

ENV MOD_OAUTH2_VERSION 3.2.0
ENV MOD_OAUTH2_PKG mod_oauth2-${MOD_OAUTH2_VERSION}-1.el7.x86_64.rpm
COPY ${MOD_OAUTH2_PKG} /root/${MOD_OAUTH2_PKG}
RUN ${CMD_PREFIX} yum localinstall -y /root/${MOD_OAUTH2_PKG}

RUN yum install -y httpd mod_ssl
ADD ssl.conf /etc/httpd/conf.d/
RUN /usr/sbin/httpd -k start && curl -k -v -s https://localhost/protected/ 2>&1 | grep "invalid_request"
```

**Comment by GRRedWings** [comment]
As always thank you for the quick response. I was able to get this to run, though I did not think ahead that this image would be ~1.4GB, Do have you, or do you think that one could easily apply your mod_oauth2 to the standard httpd:2.4  or httpd:2.4-alpine image?  

I'm still working on my understanding of docker and building upon existing images.

**Comment by zandbelt** [comment]
absolutely, people have done this before https://github.com/zmartzone/mod_auth_openidc/blob/master/Dockerfile-alpine
