### ISSUE TITLE
Exp not being honored properly for jwk

### ISSUE THREAD

**Issue by GRRedWings** [zmartzone/mod_oauth2#14]
I have a jwk location configured with the following parameters

`verify.iat=skip&verify.exp=required`

I have also tried it without the verify.exp.  But what I'm noticing is that for my token configured with 1 minute between iat and exp, that the token is valid for exactly 3 or 4 minutes after the exp has past.  Is this expected?

**Comment by zandbelt** [comment]
the verification results are cached for 5 minutes by default, without additional checking, for performance reasons; you can set the expiry of the cache with `expiry=<seconds>`

**Comment by GRRedWings** [comment]
Thanks for the quick reply. I saw that config for other types, but I wasn't sure if jwk honored it, and based on the other types I had tried jwk.expiry, just just expiry.

I also wasn't sure if jwk was using cache as there is no external IDP to authenticate against.

**Comment by zandbelt** [comment]
for the record: we're talking about JWTs here, not JWKs

**Comment by GRRedWings** [comment]
So to try to make sure we are talking the same thing, I created this config

`      OAuth2TokenVerify jwk "{\"kty\":\"RSA\",\"e\":\"AQAB\",\"use\":\"sig\",\"alg\":\"RS256\",\"n\":\"LONG KEY\"}" verify.iat=skip&expiry=5`

So I have configured the verification type of jwk, and i'm passing in a bearer token.
