### ISSUE TITLE
How to match scope value made up of multiple words 

### ISSUE THREAD

**Issue by pselvini** [zmartzone/mod_oauth2#26]
Hi,
I need to find how to correctly state a "Require" directive with AuthType oauth20, such that it matches a token with scope = "openid user:read".
None of the following works:

Require claim scope:openid user:read
Require claim scope:"openid user:read"
Require claim scope:openid\ user:read
Require claim scope:"openid\ user:read"

Could you please help me?
thanks!

**Comment by zandbelt** [comment]
assuming that were dealing with a multi-value claim, yes

**Comment by pselvini** [comment]
OK, and do you know if mod_oauth2 is available as a binary package for the most common and recent Linux distros like mod_auth_openidc, or should I build it from the sources?
I cannot find it in the Ubuntu 20.04 repository...
