### ISSUE TITLE
Set introspection request body 

### ISSUE THREAD

**Issue by nervousapps** [zmartzone/mod_oauth2#3]
Hi,

How can I set the body of the introspection request ?

Like in mod_auth_openidc : 
OIDCOAuthIntrospectionEndpointParams "uri=[]&method=[]&token=[]"

I have the following conf for token introspection : 
OAuth2TokenVerify introspect https://auth:2626/token_introspection introspect.ssl_verify=false

My auth server require a request body with the following parameters : 
method=[]
uri=[]
token[]

Thanks

**Comment by zandbelt** [comment]
that's not possible since it is not configurable

**Comment by nervousapps** [comment]
So I have to stay with mod_auth_openidc even if it is deprecated ... ? :(

**Comment by zandbelt** [comment]
you can probably get your money back
