### ISSUE TITLE
Cache value size is too large

### ISSUE THREAD

**Issue by GRRedWings** [zmartzone/mod_oauth2#34]
I saw these messages in my log, and I'm wondering if I'm doing something wrong, or if something has changed with Microsoft. Is it possible to allow for a larger value?

[Thu Jul 21 19:03:29.454826 2022] [oauth2:error] [pid 93:tid 140185836705536] [client 172.1.5.1:51198] oauth2_cache_shm_check_value: could not store value since value size is too large (11106 > 8192)
[Thu Jul 21 19:03:29.454855 2022] [oauth2:error] [pid 93:tid 140185836705536] [client 172.1.5.1:51198] oauth2_cache_set: leave: could NOT store: https://login.microsoftonline.com/86e80137-24cb-4b7f-ad48-3e322110abc6/discovery/v2.0/keys

In looking at the the configure file I'm thinking that maybe i need to use the max_val_size paramter.

If I modified my Oauth2TokenVerify to something like this, would that be the proper setup?

OAuth2TokenVerify jwks_uri https://login.microsoftonline.com/${AZURE_TENANT_ID}/discovery/v2.0/keys verify.iat=skip&max_val_size=12000

or is there some other mis-configuration that has me getting this?

**Comment by zandbelt** [comment]
you can either modify the default cache slot size by using:
```apache
OAuth2Cache shm max_val_size=16384
```
which also affects e.g. the access token verification cache, or create a dedicated cache for the `jwks_uri` and use it as follows:
```apache
OAuth2Cache shm name=keys&max_val_size=12000
OAuth2TokenVerify jwks_uri  https://login.microsoftonline.com/${AZURE_TENANT_ID}/discovery/v2.0/keys verify.iat=skip&jwks_uri.cache=keys
```
