### ISSUE TITLE
Export access token claims

### ISSUE THREAD

**Issue by babelouest** [zmartzone/mod_oauth2#35]
Hello,

Is it possible to transfer access token claims in the header, something like `OIDCOAuthRemoteUserClaim` in the [mod_auth_openidc](https://github.com/zmartzone/mod_auth_openidc) ?

**Comment by zandbelt** [comment]
claims are set by default in `OAUTH2_CLAIM_*` headers and `sub` is used to set the `REMOTE_USER` header; you can configure the behavior with `OAuth2TargetPass`, see https://github.com/zmartzone/mod_oauth2/blob/master/oauth2.conf#L138-L150

**Comment by babelouest** [comment]
Thanks, that seems to be exactly what I need!
