### ISSUE TITLE
Segmentation fault when request is proxied without Authorization header.

### ISSUE THREAD

**Issue by bartjanssens92** [zmartzone/mod_oauth2#40]
We have a loadbalancer in front of two httpd nodes with versions:
httpd.x86_64  2.4.6-67.el7.centos.6
liboauth2.x86_64  1.4.4.2-1.el7
liboauth2-apache.x86_64 1.4.4.2-1.el7
mod_auth_openidc.x86_64 2.4.3-1.el7 

When requesting an url that would require authentication via the proxy we get a 502 returned and the logs show a segmentation fault. When trying the same request directly to one of the balance members this error is not generated and the expected result is returned ( an empty directory ).

We found that if the Authorization header is missing in the request via the proxy this segfault is generated but when it is set to an invalid one it does return the empty directory. So adding `RequestHeader setIfEmpty Authorization "Bearer: empty"` in our proxy configuration fixed the issue. We are unsure if this is intended behavior or not.

Attached the debug output from both requests:
[direct_sanitized.txt](https://github.com/zmartzone/mod_oauth2/files/10206358/direct_sanitized.txt)
[via_proxy_sanitized.txt](https://github.com/zmartzone/mod_oauth2/files/10206359/via_proxy_sanitized.txt)

**Comment by zandbelt** [comment]
I'm a bit confused by the versions you use: mod_auth_openidc 2.4.2 is not dependent on liboauth2 and it seems you're not using/loadmin mod_oauth2? please clarify

**Comment by bartjanssens92** [comment]
We are using both mod_auth_openidc and mod_oauth2, I did forget to add what version in my paste. This would be:
mod_oauth2.x86_64  3.2.2-1.el7
In our apache configuration on the balance member nodes we have the following:
```apache
<LocationMatch "^\/download\/WORLDCOVER\/ESA_WORLDCOVER_10M_2021_V200\/S2RGBNIR\/.*(\.tif)+$">
  <If "%{HTTP:Authorization} =~ /Bearer/">
    AuthType oauth2
      Require valid-user
  </If>
  <Else>
    AuthType openid-connect
      Require valid-user
  </Else>
</LocationMatch>
```

**Comment by zandbelt** [comment]
it seems you're running into:
https://github.com/zmartzone/mod_auth_openidc/commit/fdbd131b386301a6b07e718bfe345d2afc3d094c
so if you'd. use a more recent version of mod_auth_openidc it would tell you that you have not correctly configured the module for the "AuthType openid-connect" use case, ie. `OIDCClientID` etc. need to be set

**Comment by bartjanssens92** [comment]
After updating the module I get an configuration error indeed. Thank you for your help!
