### ISSUE TITLE
Access Token fails to validate, "No bearer token found in request"

### ISSUE THREAD

**Issue by aniabraham** [zmartzone/mod_oauth2#6]
I was trying to migrate from the OAuth 2.0 Resource Server to this module since it's been deprecated.
I get a `Bearer error="invalid_request", error_description="No bearer token found in the request." ` whenever trying to validate the request. 

Here is the stack trace for the error
```
[Mon Aug 03 17:41:01.621503 2020] [ssl:debug] [pid 2563] ssl_engine_kernel.c(1891): [client {client_ip}] AH02043: SSL virtual host for servername {hostname} found
[Mon Aug 03 17:41:01.763582 2020] [ssl:info] [pid 2563] [client {client_ip}] AH02008: SSL library error 1 in handshake (server {hostname}:443)
[Mon Aug 03 17:41:01.763639 2020] [ssl:info] [pid 2563] SSL Library Error: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown (SSL alert number 46)
[Mon Aug 03 17:41:01.763647 2020] [ssl:info] [pid 2563] [client {client_ip}] AH01998: Connection closed to child 0 with abortive shutdown (server {hostname}:443)
[Mon Aug 03 17:41:01.764073 2020] [ssl:info] [pid 2569] [client {client_ip}] AH01964: Connection to child 6 established (server {hostname}:443)
[Mon Aug 03 17:41:01.764189 2020] [ssl:debug] [pid 2569] ssl_engine_kernel.c(1891): [client {client_ip}] AH02043: SSL virtual host for servername {hostname} found
[Mon Aug 03 17:41:01.828553 2020] [ssl:debug] [pid 2569] ssl_engine_kernel.c(1824): [client {client_ip}] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
[Mon Aug 03 17:41:01.893904 2020] [ssl:debug] [pid 2569] ssl_engine_kernel.c(225): [client {client_ip}] AH02034: Initial (No.1) HTTPS request received for child 6 (server {hostname}:443), referer:{incoming_url}
[Mon Aug 03 17:41:01.893970 2020] [authz_core:debug] [pid 2569] mod_authz_core.c(809): [client {client_ip}] AH01626: authorization result of Require valid-user : denied (no authenticated user yet), referer:{incoming_url}
[Mon Aug 03 17:41:01.893991 2020] [authz_core:debug] [pid 2569] mod_authz_core.c(809): [client {client_ip}] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer:{incoming_url}
[Mon Aug 03 17:41:01.894000 2020] [auth_openidc:debug] [pid 2569] src/mod_auth_openidc.c(3918): [client {client_ip}] oidc_check_user_id: incoming request: "/app-ui?(null)", ap_is_initial_req(r)=1, referer:{incoming_url}
[Mon Aug 03 17:41:01.894025 2020] [oauth2:debug] [pid 2569] src/http.c(154): [client {client_ip}] _oauth2_http_request_header_set_add_sanitized: Host: {hostname}:8443, referer:{incoming_url}
[Mon Aug 03 17:41:01.894033 2020] [oauth2:debug] [pid 2569] src/http.c(154): [client {client_ip}] _oauth2_http_request_header_set_add_sanitized: Connection: keep-alive, referer:{incoming_url}
[Mon Aug 03 17:41:01.894038 2020] [oauth2:debug] [pid 2569] src/http.c(154): [client {client_ip}] _oauth2_http_request_header_set_add_sanitized: Accept: */*, referer:{incoming_url}
[Mon Aug 03 17:41:01.894042 2020] [oauth2:debug] [pid 2569] src/http.c(154): [client {client_ip}] _oauth2_http_request_header_set_add_sanitized: Access-Control-Request-Method: POST, referer:{incoming_url}
[Mon Aug 03 17:41:01.894047 2020] [oauth2:debug] [pid 2569] src/http.c(154): [client {client_ip}] _oauth2_http_request_header_set_add_sanitized: Access-Control-Request-Headers: authorization,content-type, referer:{incoming_url}

[Mon Aug 03 17:41:01.894052 2020] [oauth2:debug] [pid 2569] src/http.c(154): [client {client_ip}] _oauth2_http_request_header_set_add_sanitized: Origin: http://localhost:4200, referer:{incoming_url}
[Mon Aug 03 17:41:01.894056 2020] [oauth2:debug] [pid 2569] src/http.c(154): [client {client_ip}] _oauth2_http_request_header_set_add_sanitized: Sec-Fetch-Mode: cors, referer:{incoming_url}
[Mon Aug 03 17:41:01.894060 2020] [oauth2:debug] [pid 2569] src/http.c(154): [client {client_ip}] _oauth2_http_request_header_set_add_sanitized: Sec-Fetch-Site: cross-site, referer:{incoming_url}
[Mon Aug 03 17:41:01.894063 2020] [oauth2:debug] [pid 2569] src/http.c(154): [client {client_ip}] _oauth2_http_request_header_set_add_sanitized: Sec-Fetch-Dest: empty, referer:{incoming_url}
[Mon Aug 03 17:41:01.894069 2020] [oauth2:debug] [pid 2569] src/http.c(154): [client {client_ip}] _oauth2_http_request_header_set_add_sanitized: Referer:{incoming_url}, referer:{incoming_url}
[Mon Aug 03 17:41:01.894075 2020] [oauth2:debug] [pid 2569] src/http.c(154): [client {client_ip}] _oauth2_http_request_header_set_add_sanitized: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36, referer:{incoming_url}
[Mon Aug 03 17:41:01.894083 2020] [oauth2:debug] [pid 2569] src/http.c(154): [client {client_ip}] _oauth2_http_request_header_set_add_sanitized: Accept-Encoding: gzip, deflate, br, referer:{incoming_url}
[Mon Aug 03 17:41:01.894087 2020] [oauth2:debug] [pid 2569] src/http.c(154): [client {client_ip}] _oauth2_http_request_header_set_add_sanitized: Accept-Language: en-US,en;q=0.9, referer:{incoming_url}
[Mon Aug 03 17:41:01.894092 2020] [oauth2:debug] [pid 2569] src/server/apache.c(280): [client {client_ip}] oauth2_apache_request_context_init: created request context: 0x56124ffbba20, referer:{incoming_url}
[Mon Aug 03 17:41:01.894097 2020] [oauth2:debug] [pid 2569] src/mod_oauth2.c(190): [client {client_ip}] oauth2_check_user_id_handler: incoming request: "/endpoint?(null)" ap_is_initial_req=1, referer:{incoming_url}
[Mon Aug 03 17:41:01.894101 2020] [oauth2:debug] [pid 2569] src/mod_oauth2.c(107): [client {client_ip}] oauth2_request_handler: enter, referer:{incoming_url}
[Mon Aug 03 17:41:01.894109 2020] [oauth2:debug] [pid 2569] src/proto.c(45): [client {client_ip}] _oauth2_get_source_token_from_header: enter, referer:{incoming_url}
[Mon Aug 03 17:41:01.894115 2020] [oauth2:debug] [pid 2569] src/util.c(905): [client {client_ip}] oauth2_nv_list_get: Authorization=(null), referer:{incoming_url}
[Mon Aug 03 17:41:01.894131 2020] [oauth2:debug] [pid 2569] src/proto.c(84): [client {client_ip}] _oauth2_get_source_token_from_header: leave: (null), referer:{incoming_url}
[Mon Aug 03 17:41:01.894135 2020] [oauth2:debug] [pid 2569] src/proto.c(341): [client {client_ip}] oauth2_get_source_token: no source token found in any of the configured methods: 2, referer:{incoming_url}
[Mon Aug 03 17:41:01.894139 2020] [oauth2:debug] [pid 2569] src/server/apache.c(321): [client {client_ip}] oauth2_apache_return_www_authenticate: enter, referer:{incoming_url}
[Mon Aug 03 17:41:01.894144 2020] [oauth2:debug] [pid 2569] src/server/apache.c(413): [client {client_ip}] oauth2_apache_hdr_out_add: WWW-Authenticate: Bearer error="invalid_request", error_description="No bearer token found in the request.", referer:{incoming_url}
[Mon Aug 03 17:41:01.894148 2020] [oauth2:debug] [pid 2569] src/server/apache.c(345): [client {client_ip}] oauth2_apache_return_www_authenticate: leave, referer:{incoming_url}
[Mon Aug 03 17:41:01.894152 2020] [oauth2:debug] [pid 2569] src/mod_oauth2.c(153): [client {client_ip}] oauth2_request_handler: leave, referer:{incoming_url}
[Mon Aug 03 17:41:01.894242 2020] [oauth2:debug] [pid 2569] src/server/apache.c(289): [client {client_ip}] oauth2_apache_request_context_free: dispose request context: 0x56124ffbba20, referer:{incoming_url}
[Mon Aug 03 17:41:06.899343 2020] [ssl:info] [pid 2569] (70007)The timeout specified has expired: [client {client_ip}] AH01991: SSL input filter read failed.
[Mon Aug 03 17:41:06.899439 2020] [ssl:debug] [pid 2569] ssl_engine_io.c(993): [client {client_ip}] AH02001: Connection closed to child 6 with standard shutdown (server )
```

This is my ssl.conf for the specific incoming port
```
AuthType oauth2
OAuth2TokenVerify jwks_uri https://{{keycloak_jwks_uri}} jwks_uri.ssl_verify=false
OAuth2AcceptTokenIn header name=Authorization
Require valid-user
```

The previous library still works fine with the same url and configuration. The incoming request does in fact have the Authorization header with the bearer access_token as it's value. Wondering what else do I need to change to make it work with this new module. Any help is appreciated!

**Comment by zandbelt** [comment]
I don't think the token is presented right since the Authorization header does not show up in the `_oauth2_http_request_header_set_add_sanitized` traces , nor `oauth2_nv_list_get: Authorization=(null)` but I would firstly comment out `Auth2AcceptTokenIn header name=Authorization` since you want to go with the default, which interprets a "bearer" variant

**Comment by aniabraham** [comment]
Commented out Auth2AcceptTokenIn header name=Authorization and that didn't work.
You might be right about the Authorization header not being present but it is in fact present in the request the client makes but Apache is probably removing it. Curious to know why it doesn't remove the authorization header with the OAuth 2.0 Resource Server module.

**Comment by kannan-saran** [comment]
Similar invalid_token issue but different cause for remote user. Please clarify if anything missing

WWW-Authenticate: Bearer error="invalid_token", error_description="Could not determine remote user."

Apache configuration:
--------------
  AuthType oauth2
  OAuth2TokenVerify introspect  https://somefqdn.com/atoken/introspection introspect.ssl_verify=false&introspect.auth=client_secret_post&client_id=someclientID&client_secret=somesecret
  Require valid-user
---------------

logs:
----------------------

[Wed Oct 14 13:25:47.316907 2020] [authz_core:debug] [pid 12113:tid 139649737496320] mod_authz_core.c(818): [client 3.233.78.13:1564] AH01626: authorization result
 of Require valid-user : denied (no authenticated user yet)
[Wed Oct 14 13:25:47.316920 2020] [authz_core:debug] [pid 12113:tid 139649737496320] mod_authz_core.c(818): [client 3.233.78.13:1564] AH01626: authorization result
 of <RequireAny>: denied (no authenticated user yet)
[Wed Oct 14 13:25:47.316939 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/http.c(154): [client 3.233.78.13:1564] _oauth2_http_request_header_set_add_san
itized: Host: xxxx
[Wed Oct 14 13:25:47.316947 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/http.c(154): [client 3.233.78.13:1564] _oauth2_http_request_header_set_add_san
itized: User-Agent: curl/7.70.0
[Wed Oct 14 13:25:47.316951 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/http.c(154): [client 3.233.78.13:1564] _oauth2_http_request_header_set_add_san
itized: Accept: */*
[Wed Oct 14 13:25:47.316955 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/http.c(154): [client 3.233.78.13:1564] _oauth2_http_request_header_set_add_san
itized: Authorization: Bearer 0003VsrMnN0s58CXeK0yLbOfVRqn
[Wed Oct 14 13:25:47.316959 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/http.c(154): [client 3.233.78.13:1564] _oauth2_http_request_header_set_add_san
itized: access_token: 0003VsrMnN0s58CXeK0yLbOfVRqn
[Wed Oct 14 13:25:47.316963 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/server/apache.c(280): [client 3.233.78.13:1564] oauth2_apache_request_context_
init: created request context: 0x7f02b4010380
[Wed Oct 14 13:25:47.316971 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/mod_oauth2.c(190): [client 3.233.78.13:1564] oauth2_check_user_id_handler: inc
oming request: "/index.html?(null)" ap_is_initial_req=1
[Wed Oct 14 13:25:47.316975 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/mod_oauth2.c(107): [client 3.233.78.13:1564] oauth2_request_handler: enter
[Wed Oct 14 13:25:47.316980 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/proto.c(212): [client 3.233.78.13:1564] _oauth2_get_source_token_from_envvar:
enter
[Wed Oct 14 13:25:47.316985 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/server/apache.c(491): [client 3.233.78.13:1564] oauth2_apache_get_envvar: get
environment variable: access_token
[Wed Oct 14 13:25:47.316988 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/proto.c(226): [client 3.233.78.13:1564] _oauth2_get_source_token_from_envvar: no source token found in access_token environment variable
[Wed Oct 14 13:25:47.316991 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/proto.c(45): [client 3.233.78.13:1564] _oauth2_get_source_token_from_header: enter
[Wed Oct 14 13:25:47.316995 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(905): [client 3.233.78.13:1564] oauth2_nv_list_get: Authorization=Bearer 0003VsrMnN0s58CXeK0yLbOfVRqn
[Wed Oct 14 13:25:47.316999 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/proto.c(58): [client 3.233.78.13:1564] _oauth2_get_source_token_from_header: Authorization header found
[Wed Oct 14 13:25:47.317003 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/proto.c(84): [client 3.233.78.13:1564] _oauth2_get_source_token_from_header: leave: 0003VsrMnN0s58CXeK0yLbOfVRqn
[Wed Oct 14 13:25:47.317006 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/oauth2.c(706): [client 3.233.78.13:1564] oauth2_token_verify: enter
[Wed Oct 14 13:25:47.317009 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/cache.c(402): [client 3.233.78.13:1564] oauth2_cache_get: enter: key=0003VsrMnN0s58CXeK0yLbOfVRqn, type=shm, decrypt=0
[Wed Oct 14 13:25:47.317013 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/cache.c(371): [client 3.233.78.13:1564] _oauth2_cache_hash_key: enter: key=0003VsrMnN0s58CXeK0yLbOfVRqn, algo=(null)
[Wed Oct 14 13:25:47.317016 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/jose.c(117): [client 3.233.78.13:1564] oauth2_jose_hash_bytes: enter
[Wed Oct 14 13:25:47.317057 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/jose.c(167): [client 3.233.78.13:1564] oauth2_jose_hash_bytes: leave: 1
[Wed Oct 14 13:25:47.317072 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/cache.c(386): [client 3.233.78.13:1564] _oauth2_cache_hash_key: leave: hashed key: cc7219952e99c08ddee9df2e62bbe3855133866be7bda6ac1379cba64b887bd5
[Wed Oct 14 13:25:47.317075 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/cache/shm.c(251): [client 3.233.78.13:1564] oauth2_cache_shm_get: enter
[Wed Oct 14 13:25:47.317748 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/cache/shm.c(309): [client 3.233.78.13:1564] oauth2_cache_shm_get: leave: 1
[Wed Oct 14 13:25:47.317762 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/cache.c(429): [client 3.233.78.13:1564] oauth2_cache_get: leave: cache miss for key: 0003VsrMnN0s58CXeK0yLbOfVRqn return: 0 bytes
[Wed Oct 14 13:25:47.317765 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/oauth2.c(376): [client 3.233.78.13:1564] _oauth2_introspect_verify: enter
[Wed Oct 14 13:25:47.317772 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/http.c(738): [client 3.233.78.13:1564] _oauth2_http_url_encode_list: processing: token=0003VsrMnN0s58CXeK0yLbOfVRqn
[Wed Oct 14 13:25:47.317775 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(264): [client 3.233.78.13:1564] oauth2_url_encode: enter: token
[Wed Oct 14 13:25:47.317813 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(289): [client 3.233.78.13:1564] oauth2_url_encode: leave: token
[Wed Oct 14 13:25:47.317822 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(264): [client 3.233.78.13:1564] oauth2_url_encode: enter: 0003VsrMnN0s58CXeK0yLbOfVRqn
[Wed Oct 14 13:25:47.317827 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(289): [client 3.233.78.13:1564] oauth2_url_encode: leave: 0003VsrMnN0s58CXeK0yLbOfVRqn
[Wed Oct 14 13:25:47.317832 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/http.c(738): [client 3.233.78.13:1564] _oauth2_http_url_encode_list: processing: token_type_hint=access_token
[Wed Oct 14 13:25:47.317834 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(264): [client 3.233.78.13:1564] oauth2_url_encode: enter: token_type_hint
[Wed Oct 14 13:25:47.317839 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(289): [client 3.233.78.13:1564] oauth2_url_encode: leave: token_type_hint
[Wed Oct 14 13:25:47.317841 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(264): [client 3.233.78.13:1564] oauth2_url_encode: enter: access_token
[Wed Oct 14 13:25:47.317845 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(289): [client 3.233.78.13:1564] oauth2_url_encode: leave: access_token
[Wed Oct 14 13:25:47.317849 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/http.c(738): [client 3.233.78.13:1564] _oauth2_http_url_encode_list: processing: client_id=someclientID
[Wed Oct 14 13:25:47.317852 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(264): [client 3.233.78.13:1564] oauth2_url_encode: enter: client_id
[Wed Oct 14 13:25:47.317856 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(289): [client 3.233.78.13:1564] oauth2_url_encode: leave: client_id
[Wed Oct 14 13:25:47.317861 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(264): [client 3.233.78.13:1564] oauth2_url_encode: enter: someclientID
[Wed Oct 14 13:25:47.317866 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(289): [client 3.233.78.13:1564] oauth2_url_encode: leave: someclientID
[Wed Oct 14 13:25:47.317869 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/http.c(738): [client 3.233.78.13:1564] _oauth2_http_url_encode_list: processing: client_secret=somesecret
[Wed Oct 14 13:25:47.317872 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(264): [client 3.233.78.13:1564] oauth2_url_encode: enter: client_secret
[Wed Oct 14 13:25:47.317876 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(289): [client 3.233.78.13:1564] oauth2_url_encode: leave: client_secret
[Wed Oct 14 13:25:47.317879 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(264): [client 3.233.78.13:1564] oauth2_url_encode: enter: somesecret
[Wed Oct 14 13:25:47.317883 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/util.c(289): [client 3.233.78.13:1564] oauth2_url_encode: leave: somesecret
[Wed Oct 14 13:25:47.317887 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/http.c(814): [client 3.233.78.13:1564] oauth2_http_url_form_encode: data=token
=0003VsrMnN0s58CXeK0yLbOfVRqn&token_type_hint=access_token&client_id=someclientID&client_secret=somesecret
[Wed Oct 14 13:25:47.317897 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/http.c(910): [client 3.233.78.13:1564] oauth2_http_call: enter: url=https://somefqdn.com/atoken/introspection, data=token=0003VsrMnN0s58CXeK0yLbOfVRqn&token_type_hint=access_token&client_id=someclientID&client_secret=somesecret, ctx=[ hdr=[ Content-Type=application/x-www-form-urlencoded ] cookie=[ ] ]
[Wed Oct 14 13:25:47.792899 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/http.c(1032): [client 3.233.78.13:1564] oauth2_http_call: HTTP response code=200
[Wed Oct 14 13:25:47.793081 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/http.c(1051): [client 3.233.78.13:1564] oauth2_http_call: leave [1]: {"scope":"openid profile","active":true,"token_type":"Bearer","exp":1602698580,"client_id":"someclientID","username":"someuser"}
[Wed Oct 14 13:25:47.793182 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/oauth2.c(451): [client 3.233.78.13:1564] _oauth2_introspect_verify: leave: 1
[Wed Oct 14 13:25:47.793195 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/cache.c(450): [client 3.233.78.13:1564] oauth2_cache_set: enter: key=0003VsrMnN0s58CXeK0yLbOfVRqn, len=134, ttl(s)=300, type=shm, encrypt=0
[Wed Oct 14 13:25:47.793200 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/cache.c(371): [client 3.233.78.13:1564] _oauth2_cache_hash_key: enter: key=0003VsrMnN0s58CXeK0yLbOfVRqn, algo=(null)
[Wed Oct 14 13:25:47.793204 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/jose.c(117): [client 3.233.78.13:1564] oauth2_jose_hash_bytes: enter
[Wed Oct 14 13:25:47.793222 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/jose.c(167): [client 3.233.78.13:1564] oauth2_jose_hash_bytes: leave: 1
[Wed Oct 14 13:25:47.793231 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/cache.c(386): [client 3.233.78.13:1564] _oauth2_cache_hash_key: leave: hashed key: cc7219952e99c08ddee9df2e62bbe3855133866be7bda6ac1379cba64b887bd5
[Wed Oct 14 13:25:47.793234 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/cache/shm.c(341): [client 3.233.78.13:1564] oauth2_cache_shm_set: enter
[Wed Oct 14 13:25:47.793265 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/cache/shm.c(437): [client 3.233.78.13:1564] oauth2_cache_shm_set: leave: 1
[Wed Oct 14 13:25:47.793274 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/cache.c(479): [client 3.233.78.13:1564] oauth2_cache_set: leave: successfully stored: 0003VsrMnN0s58CXeK0yLbOfVRqn
[Wed Oct 14 13:25:47.793278 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/oauth2.c(736): [client 3.233.78.13:1564] oauth2_token_verify: leave: 1
[Wed Oct 14 13:25:47.793283 2020] [oauth2:error] [pid 12113:tid 139649737496320] [client 3.233.78.13:1564] oauth2_apache_set_request_user: remote user claim could not be found
[Wed Oct 14 13:25:47.793286 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/server/apache.c(321): [client 3.233.78.13:1564] oauth2_apache_return_www_authenticate: enter
[Wed Oct 14 13:25:47.793292 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/server/apache.c(413): [client 3.233.78.13:1564] oauth2_apache_hdr_out_add: WWW-Authenticate: Bearer error="invalid_token", error_description="Could not determine remote user."
[Wed Oct 14 13:25:47.793297 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/server/apache.c(345): [client 3.233.78.13:1564] oauth2_apache_return_www_authenticate: leave
[Wed Oct 14 13:25:47.793300 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/mod_oauth2.c(153): [client 3.233.78.13:1564] oauth2_request_handler: leave
[Wed Oct 14 13:25:47.793526 2020] [oauth2:debug] [pid 12113:tid 139649737496320] src/server/apache.c(289): [client 3.233.78.13:1564] oauth2_apache_request_context_free: dispose request context: 0x7f02b4010380


----------------------

**Comment by kannan-saran** [comment]
@zandbelt could you look into the above log and suggest if anything missing

**Comment by zandbelt** [comment]
by default it looks for the "sub" claim; you'll need to provide that claim or change it via `OAuth2TargetPass`
